# Personalize your website info here
title:            Eugene Manley, Jr.
tagline:          'Professional Website for Eugene Manley, Jr.'
description:      'Website and Blog for Eugene Manley Jr.'
url:              http://manleye.github.io
author:
  name:           'Eugene Manley, Jr.'
  url:            https://twitter.com/EugeneManley
 

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
